### ISSUE TITLE
Item View(s) Broken...

### ISSUE THREAD

**Issue by jvenator** [hulihanapplications/Opal#9]
I started fresh yesterday with a fresh fork of the master 0.72 branch (assuming I went through the process correctly...). Everything seems to function except for viewing the actual Item page. It occurs both in the back-end administration and front-end, and logged-in/not logged-in. I haven't come across any other views/pages with a similar error. The same thing happened with a previous install a week ago both via localhost and a deployment to Heroku, so I don't think it's related to my setup, but who knows...

This is the local link visited, but it occurs for any item.
http://localhost:3000/Items/view/1-test-item-a

Here is the basic page error generated:
        `SyntaxError in Items#view`

```
    Showing /Users/j/Dropbox/Rails/J/Opal/app/views/plugin_images/_view.rhtml where line #51 raised:

    /Users/j/Dropbox/Rails/J/Opal/app/views/plugin_images/_view.rhtml:51: syntax error, unexpected ',', expecting ')'
    ...ugin_images", :id => item.id} , :multipart => true) );@outpu...
    ...                               ^
    Extracted source (around line #51):

    48:                 <div style="display:none" id="new_image_box" class="box_1">
    49:                       <h2><%=  t("label.item_new", :item => plugin.model_name.human) %></h2>
    50:                        <div>
    51:                            <%= form_tag ({:action => 'create', :controller => "plugin_images", :id => item.id} , :multipart => true) %>
    52:                                <%= render :partial => "shared/image_upload_form" %>
    53:                                <br>
    54:                                <div align=center>
    Trace of template inclusion: app/views/plugin_images/_view.rhtml, app/views/items/_view_summarized.html.erb, app/views/items/view.rhtml

    Rails.root: /Users/j/Dropbox/Rails/J/Opal
```

Here's the Full Trace

```
        actionpack (3.0.3) lib/action_view/template.rb:255:in `module_eval'
        actionpack (3.0.3) lib/action_view/template.rb:255:in `compile'
        actionpack (3.0.3) lib/action_view/template.rb:134:in `block in render'
        activesupport (3.0.3) lib/active_support/notifications.rb:54:in `instrument'
        actionpack (3.0.3) lib/action_view/template.rb:127:in `render'
        actionpack (3.0.3) lib/action_view/render/partials.rb:333:in `render_partial'
        actionpack (3.0.3) lib/action_view/render/partials.rb:262:in `block in render'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `block in instrument'
        activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `instrument'
        actionpack (3.0.3) lib/action_view/render/partials.rb:260:in `render'
        actionpack (3.0.3) lib/action_view/render/partials.rb:378:in `_render_partial'
        actionpack (3.0.3) lib/action_view/render/rendering.rb:22:in `render'
        app/views/items/_view_summarized.html.erb:122:in `block in _app_views_items__view_summarized_html_erb___3479753401111561699_2189696040_3054811763369039326'
        app/views/items/_view_summarized.html.erb:119:in `each'
        app/views/items/_view_summarized.html.erb:119:in `_app_views_items__view_summarized_html_erb___3479753401111561699_2189696040_3054811763369039326'
        actionpack (3.0.3) lib/action_view/template.rb:135:in `block in render'
        activesupport (3.0.3) lib/active_support/notifications.rb:54:in `instrument'
        actionpack (3.0.3) lib/action_view/template.rb:127:in `render'
        actionpack (3.0.3) lib/action_view/render/partials.rb:333:in `render_partial'
        actionpack (3.0.3) lib/action_view/render/partials.rb:262:in `block in render'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `block in instrument'
        activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `instrument'
        actionpack (3.0.3) lib/action_view/render/partials.rb:260:in `render'
        actionpack (3.0.3) lib/action_view/render/partials.rb:378:in `_render_partial'
        actionpack (3.0.3) lib/action_view/render/rendering.rb:22:in `render'
        app/views/items/view.rhtml:10:in `_app_views_items_view_rhtml___826905011919017058_2154305680_313758155196120206'
        actionpack (3.0.3) lib/action_view/template.rb:135:in `block in render'
        activesupport (3.0.3) lib/active_support/notifications.rb:54:in `instrument'
        actionpack (3.0.3) lib/action_view/template.rb:127:in `render'
        actionpack (3.0.3) lib/action_view/render/rendering.rb:59:in `block in _render_template'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `block in instrument'
        activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `instrument'
        actionpack (3.0.3) lib/action_view/render/rendering.rb:56:in `_render_template'
        actionpack (3.0.3) lib/action_view/render/rendering.rb:26:in `render'
        actionpack (3.0.3) lib/abstract_controller/rendering.rb:114:in `_render_template'
        actionpack (3.0.3) lib/abstract_controller/rendering.rb:108:in `render_to_body'
        actionpack (3.0.3) lib/action_controller/metal/renderers.rb:47:in `render_to_body'
        actionpack (3.0.3) lib/action_controller/metal/compatibility.rb:55:in `render_to_body'
        actionpack (3.0.3) lib/abstract_controller/rendering.rb:101:in `render_to_string'
        actionpack (3.0.3) lib/abstract_controller/rendering.rb:92:in `render'
        actionpack (3.0.3) lib/action_controller/metal/rendering.rb:17:in `render'
        actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
        activesupport (3.0.3) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
        /Users/j/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/benchmark.rb:310:in `realtime'
        activesupport (3.0.3) lib/active_support/core_ext/benchmark.rb:5:in `ms'
        actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
        actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:78:in `cleanup_view_runtime'
        activerecord (3.0.3) lib/active_record/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
        actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:39:in `render'
        actionpack (3.0.3) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
        actionpack (3.0.3) lib/action_controller/metal/mime_responds.rb:261:in `block in retrieve_response_from_mimes'
        actionpack (3.0.3) lib/action_controller/metal/mime_responds.rb:192:in `call'
        actionpack (3.0.3) lib/action_controller/metal/mime_responds.rb:192:in `respond_to'
        app/controllers/items_controller.rb:64:in `view'
        actionpack (3.0.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
        actionpack (3.0.3) lib/abstract_controller/base.rb:151:in `process_action'
        actionpack (3.0.3) lib/action_controller/metal/rendering.rb:11:in `process_action'
        actionpack (3.0.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
        activesupport (3.0.3) lib/active_support/callbacks.rb:475:in `_run__2443870189375818304__process_action__2033258685885091875__callbacks'
        activesupport (3.0.3) lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
        activesupport (3.0.3) lib/active_support/callbacks.rb:93:in `run_callbacks'
        actionpack (3.0.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
        actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `block in instrument'
        activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        activesupport (3.0.3) lib/active_support/notifications.rb:52:in `instrument'
        actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
        actionpack (3.0.3) lib/action_controller/metal/rescue.rb:17:in `process_action'
        actionpack (3.0.3) lib/abstract_controller/base.rb:120:in `process'
        actionpack (3.0.3) lib/abstract_controller/rendering.rb:40:in `process'
        actionpack (3.0.3) lib/action_controller/metal.rb:138:in `dispatch'
        actionpack (3.0.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
        actionpack (3.0.3) lib/action_controller/metal.rb:178:in `block in action'
        actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in `call'
        actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
        actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:27:in `call'
        rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `block in call'
        rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in `block in recognize'
        rack-mount (0.6.14) lib/rack/mount/code_generation.rb:75:in `optimized_each'
        rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in `recognize'
        rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
        actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:492:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/head.rb:14:in `call'
        rack (1.2.3) lib/rack/methodoverride.rb:24:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/flash.rb:182:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/cookies.rb:295:in `call'
        activerecord (3.0.3) lib/active_record/query_cache.rb:32:in `block in call'
        activerecord (3.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
        activerecord (3.0.3) lib/active_record/query_cache.rb:12:in `cache'
        activerecord (3.0.3) lib/active_record/query_cache.rb:31:in `call'
        activerecord (3.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
        activesupport (3.0.3) lib/active_support/callbacks.rb:415:in `_run_call_callbacks'
        actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
        rack (1.2.3) lib/rack/sendfile.rb:107:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
        railties (3.0.3) lib/rails/rack/logger.rb:13:in `call'
        rack (1.2.3) lib/rack/runtime.rb:17:in `call'
        activesupport (3.0.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
        rack (1.2.3) lib/rack/lock.rb:11:in `block in call'
        <internal:prelude>:10:in `synchronize'
        rack (1.2.3) lib/rack/lock.rb:11:in `call'
        actionpack (3.0.3) lib/action_dispatch/middleware/static.rb:30:in `call'
        railties (3.0.3) lib/rails/application.rb:168:in `call'
        railties (3.0.3) lib/rails/application.rb:77:in `method_missing'
        railties (3.0.3) lib/rails/rack/log_tailer.rb:14:in `call'
        rack (1.2.3) lib/rack/content_length.rb:13:in `call'
        rack (1.2.3) lib/rack/handler/webrick.rb:52:in `service'
        /Users/j/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
        /Users/j/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
        /Users/j/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by jvenator** [comment]
I just encountered the issue again when attempting to upload a different logo image.

```
SyntaxError in Settings#new_change_logo

Showing /Users/j/Dropbox/Rails/J/Opal/app/views/settings/new_change_logo.html.erb where line #27 raised:

/Users/j/Dropbox/Rails/J/Opal/app/views/settings/new_change_logo.html.erb:27: syntax error, unexpected ',', expecting ')'
...', :controller => "settings"} , :multipart => true)  );@outp...
...                               ^
Extracted source (around line #27):

24:                 </table>
25:             </div>          
26:             <div align="center" class="box_1" style="margin-bottom:5px;" id="upload_logo_box">
27:                 <%= form_tag ({:action => 'change_logo', :controller => "settings"} , :multipart => true)  %>
28:                     <%= render :partial => "shared/upload_form" %>
29:                     <br>
30:                     <%= submit_tag t("single.upload"), :class => "button_1" %>
Trace of template inclusion: app/views/settings/new_change_logo.html.erb

Rails.root: /Users/j/Dropbox/Rails/J/Opal
```

**Comment by hulihanapplications** [comment]
Thanks for the testing J. I've seen a couple users get this same error when there's random whitespace in form_tag arguments. I haven't been seeing this error, during when I render views... maybe it's a ruby version issue? I'm using ruby 1.9.2p180 to test, but that's pretty much moot since the whitespace should be removed regardless.

I've removed this whitespace in the following files in commit [9eb214](https://github.com/hulihanapplications/Opal/commit/9eb2142af91cbbd80a01ad7ddd45135f0d743f88).

app/views/pages/tinymce_images.html.erb
app/views/plugin_images/_view.rhtml 
app/views/settings/new_change_logo.html.erb

Good catch! As always, let me know if you run into any other bugs. Opal 0.7.3 should be released later this week.
